language: ruby
cache:
- bundler
before_install:
  gem install bundler -v 1.15
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - smbambling@gmail.com
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-switchvox.gemspec
- gem install sensu-plugins-switchvox-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: akr+FXGRGuR/2JVNku9LecfBWhtxZSBP7HKGF4lNXUyex5RAhSs/ZfcjDNuqrbfAaKYh5GNSlEGtDffHWzE3oqIIQEDat6zGe3m0LthNZz2U7+ec2DZDvhZbKZXLQOGxrYwErQkdJ9YTFKOe9k4eBOHiuLJWOx/ITvEKh08+JldJr3SUyyQM8vF5wOxkK6vZnnhKdwm49Nk3BwbTapVtTTEqsXlGGQzOAFY2GQij7pnsFNxDJBH0Qq8GJW9lQ6DLoqFXUrBBAOGdpO8JtSw/83lRmMSPpoeuayo80R1vvR1nyNtRGcvjNsqR9XumELqRWeoVFQuxL7dEbDpjVDXPKfcDOeJJ3QrQ85RilJHLHvMTsxQPy+9u8sjTO3gmnh02MBKmObFotdYnGaPsGk2TyjnXccAx8x7zeqNpwdR9j1Pdbh5DK2dI2vwMv9zS60GrbweYt10g02MPgt/RNHZNSvNu9O2s7xs1Njw1QpZE3ifQ45zYgJ1BF9vIL6aN/8dZiXw7Px4y3q2mBt9sPWg2sefh5dGCP+QFXtqsoUu0y2BnIG+ZncwCqE3CioxgOgkTGZtr/VWWFA9nX8wjWiiwuQwTkSYS89jx7DcfgUia5yCqrXVr5UupS7/bCbL//q2C4vLTje4FLNY1enWz6J6HW8sn6HNqssBDBlybakDxXRg=
  gem: sensu-plugins-switchvox
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-switchvox
